global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "tasksync-api"
    static_configs:
      - targets: ["backend:3333"]
    metrics_path: "metrics"
    scrape_interval: 10s
    scrape_timeout: 5s
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 15s
    scrape_timeout: 10s
