name: CI/CD Pipeline

on:
  push:
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    uses: ./.github/workflows/release.yml
    secrets: inherit

  deploy:
    needs: [tests, release]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
