name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    uses: ./.github/workflows/release.yml
    secrets: inherit

  deploy:
    needs: [tests, release]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
